### ISSUE TITLE
Evaluate using gokv as storage interface

### ISSUE THREAD

**Issue by philippgille** [abraithwaite/jeff#16]
Hi, I saw your project in my GitHub feed because someone I follow starred it and when seeing the [Storage interface](https://github.com/abraithwaite/jeff/blob/d1c3e3a4816115ae0dfa6f5a617032a8709718c5/storage.go#L12) I immediately thought that it would be a great fit for a project of mine: https://github.com/philippgille/gokv

I'll paste the code here so you don't have to follow the links:

`jeff.Storage`:
```
type Storage interface {
	Store(ctx context.Context, key, value []byte, exp time.Time)
	Fetch(ctx context.Context, key []byte) (value []byte, err error)
	Delete(ctx context.Context, key []byte) error
}
```

`gokv.Store`:
```
type Store interface {
    Set(k string, v interface{}) error
    Get(k string, v interface{}) (found bool, err error)
    Delete(k string) error
    Close() error
}
```

Downsides:

- `gokv` doesn't work with contexts _yet_
- There's no expiration handling *in* the implementations, but you can save the whole item (that includes the expiration) and similarly to your memory implementation ([here](https://github.com/abraithwaite/jeff/blob/383cecc55a4ec40ab582467f88a12cc20f1c7dad/memory/memory.go#L43)), just not return it when it's expired.

Upsides:

- The main upside is the number of *implementations* for the interface. There's a simple Go map, sync.Map, FreeCache, BigCache, bbolt (a.k.a. BoltDB), BadgerDB, LevelDB, Local files, Redis, Consul, etcd, Apache ZooKeeper, Memcached, Hazelcast, Amazon DynamoDB, Amazon S3, Azure Table Storage, Google Cloud Datastore, Alibaba Cloud Tablestore, MySQL, PostgreSQL, MongoDB, CockroachDB and Apache Ignite. And more to come :)
- All implementations allow to save any struct instead of just a slice of bytes. That's useful for example to include the expiration when storing a session and allows extending the stored struct with more fields in the future

This is exactly the use case that I had in mind when creating it: As a package creator you  want your package users to to be able to use as many storage implementations as possible, so you only use a common key-value interface and then point package users to existing implementations.

Maybe you can have a look at it and then I'd love to hear what you think :)

**Comment by abraithwaite** [comment]
Hi Philipp!  Thanks for taking the time to check it out!

Unfortunately, I don't think they're a great fit.  While the number of databases you support is quite impressive, the interfaces are different enough that I don't believe that they'd go well together.

To elaborate, the choice to use byteslices was deliberate.  I don't want the implementations deciding how they were going to serialize the payload since that can introduce nuanced behaviors that I don't want to support.  The stored session is already quite extensible as it is.

I see contexts as a must-have feature as well.  When handling web requests I want to preserve the ability to cancel in-flight requests.

Finally, I really only want to support a few backends as first-class entities.  It's not too much work to implement your own for whatever you need.  In fact, you could create a sub-package of your own project and use it to inject into `jeff.New`.  That way, someone who wants to use your wide selection of storage backends can do so.
