### ISSUE TITLE
Can I replace authboss with yours?

### ISSUE THREAD

**Issue by frederikhors** [abraithwaite/jeff#30]
Excuse the question maybe very basic for you, but I'm learning day by day and I want to understand well.

I am using [authboss](https://github.com/volatiletech/authboss) for a hobby project.

But I do not need most of its features: I would just like to authenticate a user (email and password) if he has to use specific APIs.

Do you think I can replace authboss with your project?

**Comment by abraithwaite** [comment]
Honestly, I have no idea.  It really depends on exactly what you need.

What this package provides is an easy and clean way to authenticate HTTP requests using session cookies which it looks like authboss may provide.

You could potentially write some additional middleware so that the session ID can be resolved from something besides the cookie header, but I don't have any good examples of that at the moment.

**Comment by frederikhors** [comment]
How I wish something like [devise](https://github.com/heartcombo/devise) for Go!
