### ISSUE TITLE
Can you use the cookie as a storer?

### ISSUE THREAD

**Issue by frederikhors** [abraithwaite/jeff#31]
Can you use the cookie as a storer for the session instead of a backend like redis and others?

**Comment by abraithwaite** [comment]
While technically possible, I personally feel that it's an antipattern because it's hard to support revocation.

See my feelings about the subject here:  https://blog.abraithwaite.net/2018/08/14/two-sessions/

I'm open to the idea if it can be implemented cleanly with support for revocation out of the box.  It does have a number of benefits, but I haven't had the time to do the research.

**Comment by frederikhors** [comment]
Thank you very much!
